/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FMCG.WorkArea.Admin;

import FMCG.FmcgAdmin;
import Market.MarketDirectory;
import UI.MainJFrame.LoginJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sagar
 */
public class FMCGAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminWorkArea
     */
    JPanel mainWorkArea;
    FmcgAdmin fmcgAdmin;
    MarketDirectory marketDirectory;

    public FMCGAdminWorkArea(JPanel mwaJPanel, FmcgAdmin fmcgAdmin, MarketDirectory marketDirectory) {
        initComponents();
        mainWorkArea = mwaJPanel;
        this.fmcgAdmin = fmcgAdmin;
        this.marketDirectory = marketDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        fmcgAdminControlPanel = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnManageUser = new javax.swing.JButton();
        btnStatistics = new javax.swing.JButton();
        lblWelcomeSysAdmin = new javax.swing.JLabel();
        processControlStack = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(960, 640));

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        fmcgAdminControlPanel.setBackground(new java.awt.Color(52, 152, 219));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnManageUser.setText("Manage User");
        btnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserActionPerformed(evt);
            }
        });

        btnStatistics.setText("Statistics");
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });

        lblWelcomeSysAdmin.setText("Welcome Admin !");

        javax.swing.GroupLayout fmcgAdminControlPanelLayout = new javax.swing.GroupLayout(fmcgAdminControlPanel);
        fmcgAdminControlPanel.setLayout(fmcgAdminControlPanelLayout);
        fmcgAdminControlPanelLayout.setHorizontalGroup(
            fmcgAdminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fmcgAdminControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeSysAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                .addComponent(btnManageUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatistics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut)
                .addGap(36, 36, 36))
        );
        fmcgAdminControlPanelLayout.setVerticalGroup(
            fmcgAdminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fmcgAdminControlPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(fmcgAdminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(btnManageUser)
                    .addComponent(btnStatistics)
                    .addComponent(lblWelcomeSysAdmin))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(fmcgAdminControlPanel);

        processControlStack.setBackground(new java.awt.Color(204, 255, 255));
        processControlStack.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(processControlStack);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel manageUserAccountsJPanel = new ManageUserAccountsJPanel(processControlStack, fmcgAdmin);
        processControlStack.add("Manage User Accounts", manageUserAccountsJPanel);
        CardLayout layout = (CardLayout) processControlStack.getLayout();
        layout.next(processControlStack);
    }//GEN-LAST:event_btnManageUserActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
//        mainWorkArea.removeAll();
//        LoginJPanel ls = new LoginJPanel(mainWorkArea);
//        mainWorkArea.add("LoginScreen",ls);
//        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
//        layout.next(mainWorkArea);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to Logout?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            mainWorkArea.remove(this);
            Component[] componentArray = mainWorkArea.getComponents();
            //System.out.println(componentArray[1]);
            Component component = componentArray[0];
            //System.out.println(component);
            LoginJPanel loginPanel = (LoginJPanel) component;
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.previous(mainWorkArea);
            for (int i = componentArray.length - 1; i > 0; i--) {
                mainWorkArea.remove(i);
            }
            //System.out.println(mainWorkArea.getComponentCount());
        }

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed
        FmcgAdminStatisticsJpanel adminStatisticsJpanl = new FmcgAdminStatisticsJpanel(processControlStack, fmcgAdmin, marketDirectory);
        processControlStack.add("FmcgAdminStatisticsJpanl", adminStatisticsJpanl);
        CardLayout layout = (CardLayout) processControlStack.getLayout();
        layout.next(processControlStack);
    }//GEN-LAST:event_btnStatisticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JButton btnStatistics;
    private javax.swing.JPanel fmcgAdminControlPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcomeSysAdmin;
    private javax.swing.JPanel processControlStack;
    // End of variables declaration//GEN-END:variables
}
