/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Farmer.WorkArea;

import UI.FMCG.WorkArea.Admin.*;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Sagar
 */
public class DashboardCropSellingPhase extends javax.swing.JPanel {

    /**
     * Creates new form ViewCropRequirements
     */

    JPanel processControlStack;
    //ChartPanel pieChartPanel;
    
    public DashboardCropSellingPhase(JPanel jp) {
        initComponents();
        processControlStack = jp;

//        ChartPanel pieChartPanel = PieChartGenerator.createPieChartPanel();
//        panel1pie1.add(pieChartPanel);
//        panel1pie1.revalidate();
//        panel1pie1.repaint();
          createPieChartPanel();  
    }
    
    
    public static ChartPanel createPieChartPanel1() {
        // Create a sample dataset
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Category 1", 30);
        dataset.setValue("Category 2", 40);
        dataset.setValue("Category 3", 20);
        dataset.setValue("Category 4", 10);

        // Create the chart using the dataset
        JFreeChart chart = ChartFactory.createPieChart(
                "Sample Pie Chart", // Title
                dataset, // Dataset
                true, // Include legend
                true, // Include tooltips
                false); // Exclude URLs
        
        // Create a ChartPanel with the chart
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));
        return chartPanel;
    }


    
    public void createPieChartPanel() {
        // Create a sample dataset
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Category 1", 1);
        dataset.setValue("Category 2", 2);
        dataset.setValue("Category 3", 50);
        dataset.setValue("Category 4", 48);

        // Create the chart using the dataset
        JFreeChart chart1 = ChartFactory.createPieChart("Total Requirement", // Title
                dataset, // Dataset
                true, // Include legend
                true, // Include tooltips
                false); // Exclude URLs
        
        // Create the second sample dataset
        DefaultPieDataset dataset2 = new DefaultPieDataset();
        dataset2.setValue("Category A", 20);
        dataset2.setValue("Category B", 30);
        dataset2.setValue("Category C", 25);
        dataset2.setValue("Category D", 25);

        // Create the second chart using the second dataset
        JFreeChart chart2 = ChartFactory.createPieChart(
                "Total Committed", // Title
                dataset2, // Dataset
                true, // Include legend
                true, // Include tooltips
                false); // Exclude URLs

        // Create a ChartPanel with both charts
        ChartPanel chartPanel1 = new ChartPanel(chart1);
        chartPanel1.setPreferredSize(new java.awt.Dimension(300, 300)); // Set size of the ChartPanel

        // Create a ChartPanel for the second chart
        ChartPanel chartPanel2 = new ChartPanel(chart2);
        chartPanel2.setPreferredSize(new java.awt.Dimension(300, 300)); // Set size of the ChartPanel


        
        //ChartPanel pieChartPanel;
        panel1pie1.add(chartPanel1);
        panel1pie1.revalidate();
        panel1pie1.repaint();
        
        panel2pie2.add(chartPanel2);
        panel2pie2.revalidate();
        panel2pie2.repaint();
        //return chartPanel;
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        panel2pie2 = new javax.swing.JPanel();
        panel1pie1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Crop Procurement");

        panel2pie2.setBackground(new java.awt.Color(255, 255, 255));
        panel2pie2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel2pie2.setPreferredSize(new java.awt.Dimension(275, 275));
        panel2pie2.setLayout(new java.awt.BorderLayout());

        panel1pie1.setBackground(new java.awt.Color(255, 255, 255));
        panel1pie1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel1pie1.setPreferredSize(new java.awt.Dimension(275, 275));
        panel1pie1.setLayout(new java.awt.BorderLayout());

        btnBack.setBackground(new java.awt.Color(0, 102, 153));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(panel1pie1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(panel2pie2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack)
                .addGap(300, 300, 300)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1pie1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(panel2pie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        processControlStack.remove(this);
        ((java.awt.CardLayout) processControlStack.getLayout()).previous(processControlStack);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panel1pie1;
    private javax.swing.JPanel panel2pie2;
    // End of variables declaration//GEN-END:variables
}
