/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Farmer.WorkArea;

import Contract.ContractDirectory;
import Farmer.FarmerProfile;
import Distributor.DistributorDirectory;
import Farmer.TransactionDirectory;
import Market.MarketDirectory;
import UI.MainJFrame.LoginJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sagar
 */
public class FarmerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form FarmerWorkArea
     */
    JPanel mainWorkArea;
    FarmerProfile farmerprofile;
    DistributorDirectory distributorDirectory;
    MarketDirectory marketDirectory;
    ContractDirectory contractDirectory;
    TransactionDirectory transactionDirectory;
    public FarmerWorkArea(JPanel jp, FarmerProfile farmerprofile,DistributorDirectory distributorDirectory, MarketDirectory marketDirectory, ContractDirectory contractDirectory, TransactionDirectory transactionDirectory) {
        initComponents();
        mainWorkArea = jp;
        this.farmerprofile = farmerprofile;
        this.contractDirectory = contractDirectory;
        this.distributorDirectory = distributorDirectory;
        this.marketDirectory = marketDirectory;
        this.transactionDirectory = transactionDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        farmerControlPanel = new javax.swing.JPanel();
        btnViewRequirements = new javax.swing.JLabel();
        btnSell = new javax.swing.JLabel();
        btnContracts = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JLabel();
        btnStatistics = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        farmerProcessStack = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 540));

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        farmerControlPanel.setBackground(new java.awt.Color(153, 204, 255));

        btnViewRequirements.setBackground(new java.awt.Color(0, 102, 153));
        btnViewRequirements.setForeground(new java.awt.Color(255, 255, 255));
        btnViewRequirements.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnViewRequirements.setText("View Requirements");
        btnViewRequirements.setOpaque(true);
        btnViewRequirements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewRequirementsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewRequirementsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewRequirementsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewRequirementsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewRequirementsMouseReleased(evt);
            }
        });

        btnSell.setBackground(new java.awt.Color(0, 102, 153));
        btnSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSell.setText("Sell Crops");
        btnSell.setOpaque(true);
        btnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSellMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSellMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSellMouseReleased(evt);
            }
        });

        btnContracts.setBackground(new java.awt.Color(0, 102, 153));
        btnContracts.setForeground(new java.awt.Color(255, 255, 255));
        btnContracts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnContracts.setText("My Contracts");
        btnContracts.setOpaque(true);
        btnContracts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContractsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContractsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContractsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnContractsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnContractsMouseReleased(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-32.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 102, 153));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setText("Logout");
        btnLogout.setOpaque(true);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoutMouseReleased(evt);
            }
        });

        btnStatistics.setBackground(new java.awt.Color(0, 102, 153));
        btnStatistics.setForeground(new java.awt.Color(255, 255, 255));
        btnStatistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStatistics.setText("Statistics");
        btnStatistics.setOpaque(true);
        btnStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatisticsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatisticsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStatisticsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStatisticsMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Farmer!");

        javax.swing.GroupLayout farmerControlPanelLayout = new javax.swing.GroupLayout(farmerControlPanel);
        farmerControlPanel.setLayout(farmerControlPanelLayout);
        farmerControlPanelLayout.setHorizontalGroup(
            farmerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmerControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(170, 170, 170)
                .addComponent(btnViewRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContracts, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        farmerControlPanelLayout.setVerticalGroup(
            farmerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmerControlPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(farmerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnViewRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContracts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(farmerControlPanel);

        farmerProcessStack.setBackground(new java.awt.Color(153, 204, 255));
        farmerProcessStack.setLayout(new java.awt.CardLayout());

        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Farmer!");
        farmerProcessStack.add(lblWelcome, "card2");

        jSplitPane1.setRightComponent(farmerProcessStack);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof javax.swing.JFrame) {
            javax.swing.JFrame frame = (javax.swing.JFrame) window;
            frame.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    
    
    private void btnViewRequirementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRequirementsMouseClicked
        // TODO add your handling code here:
        ViewCropRequirement db = new ViewCropRequirement(farmerProcessStack,farmerprofile, marketDirectory,contractDirectory);
        farmerProcessStack.add("Requirement Dashboard",db);
        CardLayout layout = (CardLayout) farmerProcessStack.getLayout();
        layout.next(farmerProcessStack);
    }//GEN-LAST:event_btnViewRequirementsMouseClicked

    private void btnViewRequirementsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRequirementsMouseEntered
        // TODO add your handling code here:
        btnViewRequirements.setBackground(Color.decode("#0EF4FB"));
    }//GEN-LAST:event_btnViewRequirementsMouseEntered

    private void btnViewRequirementsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRequirementsMouseExited
        // TODO add your handling code here:
        btnViewRequirements.setBackground(Color.decode("#CCFFFF"));
    }//GEN-LAST:event_btnViewRequirementsMouseExited

    private void btnViewRequirementsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRequirementsMousePressed
        // TODO add your handling code here:
        btnViewRequirements.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btnViewRequirementsMousePressed

    private void btnViewRequirementsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRequirementsMouseReleased
        // TODO add your handling code here:
        btnViewRequirements.setBorder(null);
    }//GEN-LAST:event_btnViewRequirementsMouseReleased


    private void btnSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseClicked
        // TODO add your handling code here:
        CropSellingJPanel csjp = new CropSellingJPanel(farmerProcessStack,farmerprofile,marketDirectory, contractDirectory,distributorDirectory,transactionDirectory);
        farmerProcessStack.add("Sell Crops",csjp);
        CardLayout layout = (CardLayout) farmerProcessStack.getLayout();
        layout.next(farmerProcessStack);
    }//GEN-LAST:event_btnSellMouseClicked

    private void btnSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseEntered
        // TODO add your handling code here:
        btnSell.setBackground(Color.decode("#0EF4FB"));
    }//GEN-LAST:event_btnSellMouseEntered

    private void btnSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseExited
        // TODO add your handling code here:
        btnSell.setBackground(Color.decode("#CCFFFF"));
    }//GEN-LAST:event_btnSellMouseExited

    private void btnSellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMousePressed
        // TODO add your handling code here:
        btnSell.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btnSellMousePressed

    private void btnSellMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseReleased
        // TODO add your handling code here:
        btnSell.setBorder(null);
    }//GEN-LAST:event_btnSellMouseReleased



    private void btnContractsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContractsMouseClicked
        // TODO add your handling code here:
        ViewFarmerContracts vfc = new ViewFarmerContracts(farmerProcessStack, farmerprofile);
        farmerProcessStack.add("View Farmer Contracts",vfc);
        CardLayout layout = (CardLayout) farmerProcessStack.getLayout();
        layout.next(farmerProcessStack);
    }//GEN-LAST:event_btnContractsMouseClicked

    private void btnContractsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContractsMouseEntered
        // TODO add your handling code here:
        btnContracts.setBackground(Color.decode("#0EF4FB"));
    }//GEN-LAST:event_btnContractsMouseEntered

    private void btnContractsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContractsMouseExited
        // TODO add your handling code here:
        btnContracts.setBackground(Color.decode("#CCFFFF"));
    }//GEN-LAST:event_btnContractsMouseExited

    private void btnContractsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContractsMousePressed
        // TODO add your handling code here:
        btnContracts.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btnContractsMousePressed

    private void btnContractsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContractsMouseReleased
        // TODO add your handling code here:
        btnContracts.setBorder(null);
    }//GEN-LAST:event_btnContractsMouseReleased


    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
//        mainWorkArea.removeAll();
//        LoginJPanel ls = new LoginJPanel(mainWorkArea);
//        mainWorkArea.add("LoginScreen",ls);
//        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
//        layout.next(mainWorkArea);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to Logout?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            mainWorkArea.remove(this);
            Component[] componentArray = mainWorkArea.getComponents();
            //System.out.println(componentArray[1]);
            Component component = componentArray[0];
            //System.out.println(component);
            LoginJPanel loginPanel = (LoginJPanel) component;
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.previous(mainWorkArea);
            for (int i = componentArray.length - 1; i > 0; i--) {
                mainWorkArea.remove(i);
            }
            //System.out.println(mainWorkArea.getComponentCount());
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(Color.decode("#006633"));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(Color.decode("#2ECC71"));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        // TODO add your handling code here:
        btnLogout.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
        // TODO add your handling code here:
        btnLogout.setBorder(null);
    }//GEN-LAST:event_btnLogoutMouseReleased

    private void btnStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticsMouseClicked
        // TODO add your handling code here:
        FarmerStatistics fs = new FarmerStatistics(marketDirectory, farmerProcessStack, farmerprofile);
        farmerProcessStack.add("Farmer Statistics", fs);
        CardLayout layout = (CardLayout) farmerProcessStack.getLayout();
        layout.next(farmerProcessStack);
    }//GEN-LAST:event_btnStatisticsMouseClicked

    private void btnStatisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticsMouseEntered
        // TODO add your handling code here:
        btnStatistics.setBackground(Color.decode("#0EF4FB"));
    }//GEN-LAST:event_btnStatisticsMouseEntered

    private void btnStatisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticsMouseExited
        // TODO add your handling code here:
        btnStatistics.setBackground(Color.decode("#CCFFFF"));
    }//GEN-LAST:event_btnStatisticsMouseExited

    private void btnStatisticsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticsMousePressed
        // TODO add your handling code here:
        btnStatistics.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btnStatisticsMousePressed

    private void btnStatisticsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticsMouseReleased
        // TODO add your handling code here:
        btnStatistics.setBorder(null);
    }//GEN-LAST:event_btnStatisticsMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnContracts;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSell;
    private javax.swing.JLabel btnStatistics;
    private javax.swing.JLabel btnViewRequirements;
    private javax.swing.JPanel farmerControlPanel;
    private javax.swing.JPanel farmerProcessStack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
