/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Farmer.WorkArea;

import Contract.Contract;
import Farmer.FarmerProfile;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sagar
 */
public class ViewFarmerContracts extends javax.swing.JPanel {

    /**
     * Creates new form ViewFarmerContracts
     */
    JPanel farmerProcessStack;
    FarmerProfile farmerProfile;
    ArrayList<Contract> farmerContracts;
    
    public ViewFarmerContracts(JPanel jp, FarmerProfile fp) {
        initComponents();
        farmerProcessStack = jp;
        this.farmerProfile = fp;
        farmerContracts = farmerProfile.getFarmerContracts();
        populateContracts();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListContracts = new javax.swing.JTable();
        lblViewContracts = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        btnBack.setBackground(new java.awt.Color(0, 102, 153));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblListContracts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Market Name", "Crop Name", "Grade", "Quantity", "QA Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListContracts);

        lblViewContracts.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblViewContracts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewContracts.setText("My Contracts and Crops Grown");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(251, 251, 251)
                        .addComponent(lblViewContracts))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblViewContracts))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        farmerProcessStack.remove(this);
        ((java.awt.CardLayout) farmerProcessStack.getLayout()).previous(farmerProcessStack);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewContracts;
    private javax.swing.JTable tblListContracts;
    // End of variables declaration//GEN-END:variables

    private void populateContracts() {
        try {
            int rc = tblListContracts.getRowCount();
            int i;
            for (i = rc - 1; i >= 0; i--) {
                ((DefaultTableModel) tblListContracts.getModel()).removeRow(i);
            }
            for (Contract contract : farmerContracts) {
                Object[] row = new Object[5];
                row[0] = contract.getMarket().getMarketName();
                row[1] = contract.getSelectedItem().getCrop().getCropName();
                row[2] = contract.getSelectedItem().getCrop().getGrade();
                row[3] = contract.getSelectedItem().getQuantity();
                row[4] = contract.isQualityAssuranceApproval();
                ((DefaultTableModel) tblListContracts.getModel()).addRow(row);
            }     
        } catch (Exception e) {
            System.out.println("Exception in Populating Farmer Contracts: " + e.getMessage());
        }
    }
}
