/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin.WorkArea;

import Business.EcoSystem;
import Business.SystemAdmin;
import UI.MainJFrame.LoginJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sagar
 */
public class SysAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminWorkArea
     */
    JPanel mainWorkArea;
    EcoSystem ecosystem;
    SystemAdmin sysAdmin;
    public SysAdminWorkArea(EcoSystem eco, JPanel mwaJPanel,SystemAdmin sa ) {
        initComponents();
        this.mainWorkArea = mwaJPanel;
        ecosystem = eco;
        sysAdmin = sa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sysadminControlPanel = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        btnManageCrops = new javax.swing.JButton();
        btnStatistics = new javax.swing.JButton();
        lblWelcomeSysAdmin = new javax.swing.JLabel();
        btnManageMarket = new javax.swing.JButton();
        sysadminProcessStack = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(960, 640));

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        sysadminControlPanel.setBackground(new java.awt.Color(255, 255, 204));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        btnManageCrops.setText("Manage Crops");
        btnManageCrops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCropsActionPerformed(evt);
            }
        });

        btnStatistics.setText("Statistics");
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });

        lblWelcomeSysAdmin.setText("Welcome System Admin !");

        btnManageMarket.setText("Manage Market");
        btnManageMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysadminControlPanelLayout = new javax.swing.GroupLayout(sysadminControlPanel);
        sysadminControlPanel.setLayout(sysadminControlPanelLayout);
        sysadminControlPanelLayout.setHorizontalGroup(
            sysadminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminControlPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblWelcomeSysAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(btnManageUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageCrops)
                .addGap(18, 18, 18)
                .addComponent(btnManageMarket)
                .addGap(18, 18, 18)
                .addComponent(btnStatistics)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap())
        );

        sysadminControlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageCrops, btnManageMarket, btnManageUsers, btnStatistics});

        sysadminControlPanelLayout.setVerticalGroup(
            sysadminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminControlPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(sysadminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(btnManageUsers)
                    .addComponent(btnManageCrops)
                    .addComponent(btnStatistics)
                    .addComponent(lblWelcomeSysAdmin)
                    .addComponent(btnManageMarket))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(sysadminControlPanel);

        sysadminProcessStack.setBackground(new java.awt.Color(255, 255, 204));
        sysadminProcessStack.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(sysadminProcessStack);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
//        mainWorkArea.removeAll();
//        LoginJPanel ls = new LoginJPanel(mainWorkArea);
//        mainWorkArea.add("LoginScreen",ls);
//        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
//        layout.next(mainWorkArea);
        
            int dialogButton =JOptionPane.YES_NO_OPTION;
            int dialogResult =JOptionPane.showConfirmDialog(null, "Would you like to Logout?","Warning", dialogButton);
            if(dialogResult==JOptionPane.YES_OPTION){
            mainWorkArea.remove(this);
            Component [] componentArray = mainWorkArea.getComponents();
            //System.out.println(componentArray[1]);
            Component component = componentArray[0];
            //System.out.println(component);
            LoginJPanel loginPanel = (LoginJPanel) component;
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.previous(mainWorkArea);
            for (int i = componentArray.length - 1; i > 0; i--) {     mainWorkArea.remove(i); }
               // System.out.println(mainWorkArea.getComponentCount());
            }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel muajp = new ManageUserAccountsJPanel(ecosystem, sysadminProcessStack, sysAdmin);
        sysadminProcessStack.add("Manage Users",muajp);
        CardLayout layout = (CardLayout) sysadminProcessStack.getLayout();
        layout.next(sysadminProcessStack);
        
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnManageCropsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCropsActionPerformed
        // TODO add your handling code here:
        ManageCrops mc = new ManageCrops(ecosystem, sysadminProcessStack);
        sysadminProcessStack.add("Manage Crops",mc);
        CardLayout layout = (CardLayout) sysadminProcessStack.getLayout();
        layout.next(sysadminProcessStack);
    }//GEN-LAST:event_btnManageCropsActionPerformed

    private void btnManageMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketActionPerformed
        // TODO add your handling code here:
        ManageMarket mm = new ManageMarket(ecosystem, sysadminProcessStack, sysAdmin);
        sysadminProcessStack.add("Manage Market",mm);
        CardLayout layout = (CardLayout) sysadminProcessStack.getLayout();
        layout.next(sysadminProcessStack);
    }//GEN-LAST:event_btnManageMarketActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed
        // TODO add your handling code here:
        Statistics ss = new Statistics(ecosystem, sysadminProcessStack);
        sysadminProcessStack.add("Statistics",ss);
        CardLayout layout = (CardLayout) sysadminProcessStack.getLayout();
        layout.next(sysadminProcessStack);
    }//GEN-LAST:event_btnStatisticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageCrops;
    private javax.swing.JButton btnManageMarket;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnStatistics;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcomeSysAdmin;
    private javax.swing.JPanel sysadminControlPanel;
    private javax.swing.JPanel sysadminProcessStack;
    // End of variables declaration//GEN-END:variables
}
