/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin.WorkArea;

import Business.EcoSystem;
import Business.SystemAdmin;
import FMCG.FMCG;
import FMCG.FMCGDirectory;
import FMCG.FmcgAdmin;
import Farmer.FarmerProfile;
import Distributor.Distributor;
import Distributor.DistributorAdmin;
import PersonUserProfile.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sagar
 */
public class ViewUserDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewUserDetails
     */
    JPanel sysadminProcessStack;
    UserAccount selectedAccount;
    EcoSystem ecosystem;
    
    public ViewUserDetails(UserAccount ua, JPanel jp, EcoSystem eco) {
        initComponents();
        sysadminProcessStack = jp;
        selectedAccount = ua;
        ecosystem = eco;
        populateUserFields();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblManageUser = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPersonID = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPersonID = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtEnterpriseName = new javax.swing.JTextField();
        txtEnterpriseType = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblManageUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblManageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUser.setText("User Details");

        lblName.setText("Name:");

        lblPersonID.setText("Person ID:");

        lblEmailID.setText("Email ID:");

        lblEnterpriseName.setText("Enterprise Name:");

        lblEnterpriseType.setText("Enterprise Type:");

        lblUserName.setText("User Name:");

        lblPassword.setText("Password:");

        txtName.setEnabled(false);

        txtPersonID.setEnabled(false);

        txtEmailID.setEnabled(false);

        txtEnterpriseName.setEnabled(false);

        txtEnterpriseType.setEnabled(false);

        txtUsername.setEnabled(false);

        txtPassword.setEnabled(false);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addComponent(lblPersonID)
                    .addComponent(lblEmailID)
                    .addComponent(lblEnterpriseName)
                    .addComponent(lblEnterpriseType)
                    .addComponent(lblUserName)
                    .addComponent(lblName))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(txtName)
                    .addComponent(txtPersonID)
                    .addComponent(txtEmailID)
                    .addComponent(txtEnterpriseName)
                    .addComponent(txtEnterpriseType)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonID)
                    .addComponent(txtPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseType)
                    .addComponent(txtEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        try {
            sysadminProcessStack.remove(this);
            Component[] componentArray = sysadminProcessStack.getComponents();
            Component component = componentArray[componentArray.length - 1];
            ManageUserAccountsJPanel manageUserAccountsJPanel = (ManageUserAccountsJPanel) component;
            manageUserAccountsJPanel.refreshUserAccountTable();
            CardLayout layout = (CardLayout) sysadminProcessStack.getLayout();
            layout.previous(sysadminProcessStack);
            
        } catch (Exception e) {
            System.out.println("Exception in back button: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        txtName.setEnabled(true);
        txtEmailID.setEnabled(true);
        txtEnterpriseName.setEnabled(true);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if(txtName.getText().isBlank()|| txtPassword.getText().isBlank()|| txtUsername.getText().isBlank() || txtEmailID.getText().isBlank() || txtEnterpriseName.getText().isBlank())
            {
                JOptionPane.showMessageDialog(null, "Please fill all details.","Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{
                if (selectedAccount.getAssociatedPersonProfile() instanceof FmcgAdmin) {
                    for (FMCG fmcg: ecosystem.getfMCGDirectory().getFmcgs()){
                         if (fmcg.getFmcgAdmin().getPerson().getFullName().equals(selectedAccount.getPersonName())){
                             fmcg.setFmcgName(txtEnterpriseName.getText());
                         }
                    }
                } else if (selectedAccount.getAssociatedPersonProfile() instanceof DistributorAdmin) {
                    for (Distributor d: ecosystem.getDistributorDirectory().getDistributors()){
                         if (d.getDistributorAdmin().getPerson().getFullName().equals(selectedAccount.getPersonName())){
                             d.setDistributorName(txtEnterpriseName.getText());
                         }
                    }  
                }
                selectedAccount.getAssociatedPersonProfile().getPerson().setFullName(txtName.getText());
                selectedAccount.getAssociatedPersonProfile().getPerson().setEmailId(txtEmailID.getText());
                selectedAccount.setUsername(txtUsername.getText());
                selectedAccount.setPassword(txtPassword.getText());
                btnSave.setEnabled(false);
                btnEdit.setEnabled(true);
                txtName.setEnabled(false);
                txtEmailID.setEnabled(false);
                txtEnterpriseName.setEnabled(false);
                txtUsername.setEnabled(false);
                txtPassword.setEnabled(false);
          }
        }
        catch (Exception e) {
            System.out.println("Exception while saving Information: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    public void populateUserFields() {
        try {
            txtName.setText(selectedAccount.getPersonName());
            txtPersonID.setText(String.valueOf(selectedAccount.getPersonId()));
            txtEmailID.setText(selectedAccount.getAssociatedPersonProfile().getPerson().getEmailId());
            txtEnterpriseType.setText(selectedAccount.getRole());
            if (selectedAccount.getAssociatedPersonProfile() instanceof FmcgAdmin) {
                    for (FMCG fmcg: ecosystem.getfMCGDirectory().getFmcgs()){
                         if (fmcg.getFmcgAdmin().getPerson().getFullName().equals(selectedAccount.getPersonName())){
                             txtEnterpriseName.setText(fmcg.getFmcgName());
                         }
                    }
                } else if (selectedAccount.getAssociatedPersonProfile() instanceof FarmerProfile) {
                    //for (FarmerProfile fp: ecosystem.getFarmerDirectory().getFarmerProfiles()){
                         //if (fp.getPerson().getFullName().equals(selectedAccount.getPersonName())){
                         txtEnterpriseName.setVisible(false);
                         lblEnterpriseName.setVisible(false);
                         txtEnterpriseName.setText("Not Applicable");
                         //}
                    //}
                } else if (selectedAccount.getAssociatedPersonProfile() instanceof DistributorAdmin) {
                    for (Distributor d: ecosystem.getDistributorDirectory().getDistributors()){
                         if (d.getDistributorAdmin().getPerson().getFullName().equals(selectedAccount.getPersonName())){
                             txtEnterpriseName.setText(d.getDistributorName());
                         }
                    }
                } else if (selectedAccount.getAssociatedPersonProfile() instanceof SystemAdmin) {
                         txtEnterpriseName.setVisible(false);
                         lblEnterpriseName.setVisible(false);
                         txtEnterpriseName.setText("Not Applicable");
                }
            txtUsername.setText(selectedAccount.getUsername());
            txtPassword.setText(selectedAccount.getPassword());
            
        } catch (Exception e) {
            System.out.println("Exception while populating Information: " + e.getMessage());
      }   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblManageUser;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtEnterpriseType;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPersonID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
