/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.MainJFrame;

import Business.ConfigureABusiness;
import Business.EcoSystem;
import UI.Distributor.WorkArea.DistributorLoginPage;
import Business.SystemAdmin;
import FMCG.FMCGDirectory;
import Farmer.FarmerProfile;
import PersonUserProfile.UserAccount;
import QualityAssurance.QualityAssuranceProfile;
import java.awt.Color;
import UI.FMCG.WorkArea.Admin.FMCGLoginPage;
import UI.Farmer.WorkArea.FarmerLoginPage;
import UI.QualityAssurance.WorkArea.CropQualityManager;
import UI.QualityAssurance.WorkArea.QualityAssuranceLoginPage;
import UI.SystemAdmin.WorkArea.SysAdminLoginPage;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.awt.Window;
import javax.swing.BorderFactory;

/**
 *
 * @author Sagar
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    JPanel mainWorkArea;
    EcoSystem ecosystem;
    SystemAdmin sysAdmin;

    public LoginJPanel(JPanel mwaJPanel, EcoSystem ecosystem) {
        //ecosystem = initializeData();
        initComponents();
        this.ecosystem = ecosystem;
        mainWorkArea = mwaJPanel;
        sysAdmin = ecosystem.getSystemAdmin();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_System_Admin = new javax.swing.JLabel();
        lblSystem = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btn_FMCG = new javax.swing.JLabel();
        btn_Quality_Assu = new javax.swing.JLabel();
        btn_Distributors = new javax.swing.JLabel();
        btn_Farmer = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        BACKGROUD = new javax.swing.JLabel();

        setBackground(new java.awt.Color(46, 204, 113));

        btn_System_Admin.setBackground(new java.awt.Color(46, 204, 113));
        btn_System_Admin.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_System_Admin.setForeground(new java.awt.Color(255, 255, 255));
        btn_System_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-setting-32.png"))); // NOI18N
        btn_System_Admin.setText(" System Admin");
        btn_System_Admin.setOpaque(true);
        btn_System_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_System_AdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_System_AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_System_AdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_System_AdminMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_System_AdminMouseReleased(evt);
            }
        });

        lblSystem.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystem.setText(" APPLICATION ENGINEERING DEVELOPMENT FINAL PROJECT [ TEAM 21 ]");

        btnExit.setBackground(new java.awt.Color(46, 204, 113));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-32.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btn_FMCG.setBackground(new java.awt.Color(46, 204, 113));
        btn_FMCG.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_FMCG.setForeground(new java.awt.Color(255, 255, 255));
        btn_FMCG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-street-food-32.png"))); // NOI18N
        btn_FMCG.setText("     FMCG");
        btn_FMCG.setOpaque(true);
        btn_FMCG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FMCGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FMCGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_FMCGMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_FMCGMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_FMCGMouseReleased(evt);
            }
        });

        btn_Quality_Assu.setBackground(new java.awt.Color(46, 204, 113));
        btn_Quality_Assu.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_Quality_Assu.setForeground(new java.awt.Color(255, 255, 255));
        btn_Quality_Assu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-quality-32.png"))); // NOI18N
        btn_Quality_Assu.setText("     Quality Assurance");
        btn_Quality_Assu.setOpaque(true);
        btn_Quality_Assu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Quality_AssuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Quality_AssuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Quality_AssuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Quality_AssuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Quality_AssuMouseReleased(evt);
            }
        });

        btn_Distributors.setBackground(new java.awt.Color(46, 204, 113));
        btn_Distributors.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_Distributors.setForeground(new java.awt.Color(255, 255, 255));
        btn_Distributors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-omnichannel-32.png"))); // NOI18N
        btn_Distributors.setText("     Distributor");
        btn_Distributors.setOpaque(true);
        btn_Distributors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DistributorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DistributorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DistributorsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DistributorsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_DistributorsMouseReleased(evt);
            }
        });

        btn_Farmer.setBackground(new java.awt.Color(46, 204, 113));
        btn_Farmer.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_Farmer.setForeground(new java.awt.Color(255, 255, 255));
        btn_Farmer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-farmer-32.png"))); // NOI18N
        btn_Farmer.setText("     Farmer");
        btn_Farmer.setOpaque(true);
        btn_Farmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FarmerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FarmerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_FarmerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_FarmerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_FarmerMouseReleased(evt);
            }
        });

        BACKGROUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MainBg.png"))); // NOI18N
        BACKGROUD.setToolTipText("");

        jLayeredPane1.setLayer(BACKGROUD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(BACKGROUD, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_Farmer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_FMCG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Distributors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Quality_Assu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                            .addComponent(btn_System_Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_System_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(btn_Farmer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_FMCG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Distributors, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Quality_Assu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof javax.swing.JFrame) {
            javax.swing.JFrame frame = (javax.swing.JFrame) window;
            frame.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed


    private void btn_System_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_System_AdminMouseClicked
        // TODO add your handling code here:
        SysAdminLoginPage sys = new SysAdminLoginPage(ecosystem, mainWorkArea, sysAdmin);
        mainWorkArea.add("SystemAdmin", sys);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_System_AdminMouseClicked

    private void btn_System_AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_System_AdminMouseEntered
        // TODO add your handling code here:
        btn_System_Admin.setBackground(Color.decode("#006633"));
    }//GEN-LAST:event_btn_System_AdminMouseEntered

    private void btn_System_AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_System_AdminMouseExited
        // TODO add your handling code here:
        btn_System_Admin.setBackground(Color.decode("#2ECC71"));
    }//GEN-LAST:event_btn_System_AdminMouseExited

    private void btn_System_AdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_System_AdminMousePressed
        // TODO add your handling code here:
        btn_System_Admin.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btn_System_AdminMousePressed

    private void btn_System_AdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_System_AdminMouseReleased
        // TODO add your handling code here:
        btn_System_Admin.setBorder(null);
    }//GEN-LAST:event_btn_System_AdminMouseReleased


    private void btn_FMCGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FMCGMouseClicked
        // TODO add your handling code here:
        FMCGLoginPage fmcglp = new FMCGLoginPage(mainWorkArea, ecosystem.getUserAccountDirectory(), ecosystem.getfMCGDirectory(), ecosystem.getMarketDirectory());
        mainWorkArea.add("FMCG Login", fmcglp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_FMCGMouseClicked

    private void btn_FMCGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FMCGMouseEntered
        // TODO add your handling code here:
        btn_FMCG.setBackground(Color.decode("#006633"));
    }//GEN-LAST:event_btn_FMCGMouseEntered

    private void btn_FMCGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FMCGMouseExited
        // TODO add your handling code here:
        btn_FMCG.setBackground(Color.decode("#2ECC71"));
    }//GEN-LAST:event_btn_FMCGMouseExited

    private void btn_FMCGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FMCGMousePressed
        // TODO add your handling code here:
        btn_FMCG.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btn_FMCGMousePressed

    private void btn_FMCGMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FMCGMouseReleased
        // TODO add your handling code here:
        btn_FMCG.setBorder(null);
    }//GEN-LAST:event_btn_FMCGMouseReleased


    private void btn_Quality_AssuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Quality_AssuMouseClicked
        // TODO add your handling code here:
        QualityAssuranceLoginPage qalp = new QualityAssuranceLoginPage(mainWorkArea, ecosystem.getContractDirectory(), ecosystem.getUserAccountDirectory());
        mainWorkArea.add("QA Login", qalp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);

    }//GEN-LAST:event_btn_Quality_AssuMouseClicked

    private void btn_Quality_AssuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Quality_AssuMouseEntered
        // TODO add your handling code here:
        btn_Quality_Assu.setBackground(Color.decode("#006633"));
    }//GEN-LAST:event_btn_Quality_AssuMouseEntered

    private void btn_Quality_AssuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Quality_AssuMouseExited
        // TODO add your handling code here:
        btn_Quality_Assu.setBackground(Color.decode("#2ECC71"));
    }//GEN-LAST:event_btn_Quality_AssuMouseExited

    private void btn_Quality_AssuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Quality_AssuMousePressed
        // TODO add your handling code here:
        btn_Quality_Assu.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btn_Quality_AssuMousePressed

    private void btn_Quality_AssuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Quality_AssuMouseReleased
        // TODO add your handling code here:
        btn_Quality_Assu.setBorder(null);
    }//GEN-LAST:event_btn_Quality_AssuMouseReleased


    private void btn_DistributorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DistributorsMouseClicked
        // TODO add your handling code here:
        DistributorLoginPage Dislp = new DistributorLoginPage(mainWorkArea, ecosystem);
        mainWorkArea.add("Distributor Login", Dislp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_DistributorsMouseClicked

    private void btn_DistributorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DistributorsMouseEntered
        // TODO add your handling code here:
        btn_Distributors.setBackground(Color.decode("#006633"));
    }//GEN-LAST:event_btn_DistributorsMouseEntered

    private void btn_DistributorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DistributorsMouseExited
        // TODO add your handling code here:
        btn_Distributors.setBackground(Color.decode("#2ECC71"));
    }//GEN-LAST:event_btn_DistributorsMouseExited

    private void btn_DistributorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DistributorsMousePressed
        // TODO add your handling code here:
        btn_Distributors.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btn_DistributorsMousePressed

    private void btn_DistributorsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DistributorsMouseReleased
        // TODO add your handling code here:
        btn_Distributors.setBorder(null);
    }//GEN-LAST:event_btn_DistributorsMouseReleased


    private void btn_FarmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FarmerMouseClicked
        // TODO add your handling code here:
        FarmerLoginPage flp = new FarmerLoginPage(mainWorkArea, ecosystem.getUserAccountDirectory(),ecosystem.getDistributorDirectory(),ecosystem.getMarketDirectory(),ecosystem.getContractDirectory(),ecosystem.getTransactionDirectory());
        mainWorkArea.add("Farmer Login",flp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btn_FarmerMouseClicked

    private void btn_FarmerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FarmerMouseEntered
        // TODO add your handling code here:
        btn_Farmer.setBackground(Color.decode("#006633"));
    }//GEN-LAST:event_btn_FarmerMouseEntered

    private void btn_FarmerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FarmerMouseExited
        // TODO add your handling code here:
        btn_Farmer.setBackground(Color.decode("#2ECC71"));
    }//GEN-LAST:event_btn_FarmerMouseExited

    private void btn_FarmerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FarmerMousePressed
        // TODO add your handling code here:
        btn_Farmer.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_btn_FarmerMousePressed

    private void btn_FarmerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FarmerMouseReleased
        // TODO add your handling code here:
        btn_Farmer.setBorder(null);
    }//GEN-LAST:event_btn_FarmerMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUD;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel btn_Distributors;
    private javax.swing.JLabel btn_FMCG;
    private javax.swing.JLabel btn_Farmer;
    private javax.swing.JLabel btn_Quality_Assu;
    private javax.swing.JLabel btn_System_Admin;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblSystem;
    // End of variables declaration//GEN-END:variables

    private EcoSystem displayData() {
        //EcoSystem ecoSystem = ConfigureABusiness.initialize();
        // Display Crops
        System.out.println("Crops Created:");
        ecosystem.getCropDirectory().getCrops().forEach(crop -> System.out.println("Crop Name: " + crop.getCropName() + ", Grade: " + crop.getGrade()));

        // Display Markets
        System.out.println("\nMarkets Created:");
        ecosystem.getMarketDirectory().getMarkets().forEach(market -> System.out.println("Market Name: " + market.getMarketName() + ", Season :" + market.getSeason()));

        // Display Distributors and their officers
        System.out.println("\nDistributors and Officers:");
        ecosystem.getDistributorDirectory().getDistributors().forEach(distributor -> {
            System.out.println("Distributor Name: " + distributor.getDistributorName());
            System.out.println("  Inventory Officers:");
            distributor.getInventoryOffice().getInventoryOfficers().forEach(officer
                    -> System.out.println("    Officer Name: " + officer.getPerson().getFullName()));
            System.out.println("  Transport Officers:");
            distributor.getTransportOffice().getTransportOfficers().forEach(officer
                    -> System.out.println("    Officer Name: " + officer.getPerson().getFullName()));
        });

        // Display FMCG entities and their offices
        System.out.println("\nFMCG Entities and Officers:");
        ecosystem.getfMCGDirectory().getFmcgs().forEach(fmcg -> {
            System.out.println("FMCG Name: " + fmcg.getFmcgName());
            System.out.println("  Requirement Officers:");
            fmcg.getRequirementOffice().getRequirementOfficers().forEach(officer
                    -> System.out.println("    Officer Name: " + officer.getPerson().getFullName()));
            System.out.println("  Procurement Officers:");
            fmcg.getProcurementOffice().getProcurementOfficers().forEach(officer
                    -> System.out.println("    Officer Name: " + officer.getPerson().getFullName()));
        });

        // Display System User Accounts
        System.out.println("\nUser Accounts:");
        ecosystem.getUserAccountDirectory().getUserAccountList().forEach(account
                -> System.out.println("Username: " + account.getUsername()
                        + ", Role: " + account.getAssociatedPersonProfile().getRole()
                        + ", Name: " + account.getPersonName()
                        + ", password " + account.getPassword()));

        // Display FMCG Accounts
        System.out.println("\nFMCG Accounts:");
        ecosystem.getfMCGDirectory().getFmcgs().forEach(fmcg -> fmcg.getFmcgUserAccountDirectory().getUserAccountList().forEach(fmcgUserAccount -> System.out.println("Username: " + fmcgUserAccount.getUsername()
                + ", Role: " + fmcgUserAccount.getAssociatedPersonProfile().getRole()
                + ", Name: " + fmcgUserAccount.getPersonName()
                + ", password " + fmcgUserAccount.getPassword())));

        // Display Distributor Accounts
        System.out.println("\nDistributor Accounts:");
        ecosystem.getDistributorDirectory().getDistributors().forEach(distributor -> distributor.getDistributorUserAccountDirectory().getUserAccountList().forEach(distributorUserAccount -> System.out.println("Username: " + distributorUserAccount.getUsername()
                + ", Role: " + distributorUserAccount.getAssociatedPersonProfile().getRole()
                + ", Name: " + distributorUserAccount.getPersonName()
                + ", password " + distributorUserAccount.getPassword())));

        System.out.println("\nFarmer Accounts:");
        for(UserAccount account: ecosystem.getUserAccountDirectory().getUserAccountList())
            if(account.getAssociatedPersonProfile() instanceof FarmerProfile){
                System.out.println("Username: " + account.getUsername()
                + ", password: " + account.getPassword()
                + ", Name: " + account.getAssociatedPersonProfile().getPerson().getFullName()
                + ", Role: " + account.getAssociatedPersonProfile().getRole());
            }
        System.out.println("\nQA Accounts:");
        for(UserAccount account: ecosystem.getUserAccountDirectory().getUserAccountList())
            if(account.getAssociatedPersonProfile() instanceof QualityAssuranceProfile){
                System.out.println("Username: " + account.getUsername()
                + ", password: " + account.getPassword()
                + ", Name: " + account.getAssociatedPersonProfile().getPerson().getFullName()
                + ", Role: " + account.getAssociatedPersonProfile().getRole());
            }
        
        return ecosystem;
    }
}
