/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distributor.WorkArea;

import Business.EcoSystem;
import Distributor.Distributor;
import Distributor.DistributorAdmin;
import Distributor.DistributorUserAccount;
import Distributor.DistributorUserAccountDirectory;
import Distributor.InventoryOfficer;
import Distributor.TransportOfficer;
import UI.FMCG.WorkArea.Admin.*;
import PersonUserProfile.Profile;
import PersonUserProfile.UserAccount;
import PersonUserProfile.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aditya
 */
public class DistributorLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form FMCGLoginPage
     */
    JPanel mainWorkArea;
    EcoSystem ecoSystem;
    
    public DistributorLoginPage(JPanel mwaJPanel, EcoSystem ecoSystem) {
        initComponents();
        this.mainWorkArea = mwaJPanel;
        this.ecoSystem = ecoSystem;
        populateDistributor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        txtUserNameField = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPasswordField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblSystem = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblSelectRole1 = new javax.swing.JLabel();
        cmbDis = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(224, 245, 166));
        setPreferredSize(new java.awt.Dimension(960, 640));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUserName.setText("User Name:");

        txtUserNameField.setPreferredSize(new java.awt.Dimension(64, 26));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblPassword.setText("Password:");

        txtPasswordField.setPreferredSize(new java.awt.Dimension(64, 26));
        txtPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordFieldActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.setMinimumSize(new java.awt.Dimension(72, 26));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLoginButtonActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin_login.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(480, 640));

        lblSystem.setBackground(new java.awt.Color(46, 204, 113));
        lblSystem.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystem.setText("DISTRIBUTOR LOGIN");

        btnExit.setBackground(new java.awt.Color(46, 204, 113));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-32.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblSelectRole1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblSelectRole1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelectRole1.setText("Select Distributor: ");

        cmbDis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmbDis, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addComponent(lblPassword)
                            .addComponent(txtUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSelectRole1))
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(187, 187, 187)
                .addComponent(btnExit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack)
                    .addComponent(btnExit))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblSelectRole1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogin, txtPasswordField, txtUserNameField});

    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFieldActionPerformed

    private void btnLoginLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLoginButtonActionPerformed
        // TODO add your handling code here:
//        String selectedDepartment = cmbRole.getSelectedItem().toString();
        Profile profile;
        String username = txtUserNameField.getText();
        String password = String.valueOf(txtPasswordField.getPassword());
        Distributor d = ecoSystem.getDistributorDirectory().searchDistributor(String.valueOf(cmbDis.getSelectedItem()));

        UserAccountDirectory uad = ecoSystem.getUserAccountDirectory();
        UserAccount useraccount = uad.AuthenticateUser(username, password);
        
        DistributorUserAccountDirectory duad= d.getDistributorUserAccountDirectory();
        DistributorUserAccount duseraccount = duad.AuthenticateUser(username, password);
        if (useraccount != null) {
            if (useraccount.getAssociatedPersonProfile() instanceof DistributorAdmin) {
            DistributorAdminWorkArea Dist_AWA = new DistributorAdminWorkArea(mainWorkArea,d.getDistributorAdmin(),ecoSystem.getMarketDirectory(), ecoSystem.getCropDirectory(), ecoSystem.getFmcgTransactionDirectory());
            mainWorkArea.add("Distributor Admin", Dist_AWA);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);     
            }
        }
        else if(duseraccount!=null){
           if (duseraccount.getAssociatedPersonProfile() instanceof InventoryOfficer) {
                String selectedDistributorName = String.valueOf(cmbDis.getSelectedItem());
                for(InventoryOfficer inventoryOfficer : d.getInventoryOffice().getInventoryOfficers()){
                    if(duseraccount.getAssociatedPersonProfile().getPerson().equals(inventoryOfficer.getPerson())){
                       InventoryOfficerWorkArea Inventory_workarea = new InventoryOfficerWorkArea(mainWorkArea,inventoryOfficer, ecoSystem);
                       mainWorkArea.add("InventoryOfficerWorkArea", Inventory_workarea);
                       CardLayout layout = (CardLayout) mainWorkArea.getLayout();
                       layout.next(mainWorkArea);
                    }
                }
            }
            else if (duseraccount.getAssociatedPersonProfile() instanceof TransportOfficer) {
                for(TransportOfficer transportOfficer : d.getTransportOffice().getTransportOfficers()){
                    if(duseraccount.getAssociatedPersonProfile().getPerson().equals(transportOfficer.getPerson())){
                       TransportOfficerOfficerWorkArea Transport_workarea = new TransportOfficerOfficerWorkArea(mainWorkArea,transportOfficer, ecoSystem);
                       mainWorkArea.add("TransportOfficerOfficerWorkArea", Transport_workarea);
                       CardLayout layout = (CardLayout) mainWorkArea.getLayout();
                       layout.next(mainWorkArea);
                    }
                }
            }
        }       
        else{
            JOptionPane.showMessageDialog(null,"Enter valid UserName or Password.");
            return;
        }
    }//GEN-LAST:event_btnLoginLoginButtonActionPerformed

    private boolean isValid(String username, String password) {
    // Hardcoded employee credentials for demonstration purposes
    return true;
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        ((java.awt.CardLayout) mainWorkArea.getLayout()).previous(mainWorkArea);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof javax.swing.JFrame) {
            javax.swing.JFrame frame = (javax.swing.JFrame) window;
            frame.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbDis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSelectRole1;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPasswordField;
    private javax.swing.JTextField txtUserNameField;
    // End of variables declaration//GEN-END:variables

    private void populateDistributor() {
        cmbDis.removeAllItems();
        for(Distributor distributor : ecoSystem.getDistributorDirectory().getDistributors()){
            cmbDis.addItem(distributor.getDistributorName());
        }
    }
}
