/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Distributor.WorkArea;



import Common.Item;
import CropFolder.Crop;
import CropFolder.CropDirectory;
import Market.MarketDirectory;
import Distributor.BuyOffer;
import Distributor.Distributor;
import Distributor.DistributorAdmin;
import Distributor.DistributorUserAccount;
import UI.FMCG.WorkArea.Admin.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Market.Market;

/**
 *
 * @author Prarthana
 */
public class ManageDistributorBuyOfferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel processControlStack;
    DistributorAdmin distributorAdmin;
    MarketDirectory marketDirectory;
    CropDirectory cropDirectory;

    ManageDistributorBuyOfferJPanel(JPanel processControlStack, DistributorAdmin distributorAdmin, MarketDirectory marketDirectory, CropDirectory cropDirectory) {
        initComponents();
        this.processControlStack = processControlStack;
        this.distributorAdmin = distributorAdmin;
        this.marketDirectory = marketDirectory;
        this.cropDirectory = cropDirectory;
//        populateSeason();
        populateTable();
//        populateCombo();
    }


        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        lblListofUsers = new javax.swing.JLabel();
        lblManageUser = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BuyOfferTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(224, 245, 166));
        setLayout(null);

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 30, 73, 23);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(790, 450, 80, 23);

        lblListofUsers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblListofUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListofUsers.setText("List of Buyoffer");
        add(lblListofUsers);
        lblListofUsers.setBounds(30, 50, 840, 17);

        lblManageUser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblManageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUser.setText("Manage BuyOffer");
        add(lblManageUser);
        lblManageUser.setBounds(30, 10, 840, 28);

        BuyOfferTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Market Name", "Crop Name", "Quantity", "Season", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(BuyOfferTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 80, 840, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
//        ViewCropRequirements vcrjp = new ViewCropRequirements(processControlStack);
//        processControlStack.add("View Crops",vcrjp);
//        CardLayout layout = (CardLayout) processControlStack.getLayout();
//        layout.next(processControlStack);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        processControlStack.remove(this);
        ((java.awt.CardLayout) processControlStack.getLayout()).previous(processControlStack);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_btnBackActionPerformed
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BuyOfferTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblListofUsers;
    private javax.swing.JLabel lblManageUser;
    // End of variables declaration//GEN-END:variables

//    private void populateSeason() {
//        cmbMarketName.removeAllItems();
//        for(Market market : marketDirectory.getMarkets()){
//            cmbMarketName.addItem(market.getMarketName());
//        }
//    }

    private void populateTable() {
        DefaultTableModel model =(DefaultTableModel)BuyOfferTable.getModel();
        model.setRowCount(0);
        for(Market market : marketDirectory.getMarkets()){
            for(BuyOffer buyOffer: market.getBuyOfferDirectory().getBuyOffers()){
                if(buyOffer.getDistributorAdmin().equals(distributorAdmin)){
                    Object[] row =new Object[5];
                    row[0]=market.getMarketName();
                    row[1]=buyOffer.getItem().getCrop().getCropName();
                    row[2]=buyOffer.getItem().getQuantity();
                    row[3]=market.getSeason();
                    row[4]=buyOffer.getUnitPrice();
                    model.addRow(row);
                }
            }
        }
    }



//    private void populateCombo() {
//        cmbCrop.removeAllItems();
//        for(Crop crop:cropDirectory.getCrops()){
//            cmbCrop.addItem(crop.getCropName()+" "+crop.getGrade());     
//        }
//    }

}
