/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distributor.WorkArea;

import UI.SystemAdmin.WorkArea.*;
import Business.EcoSystem;
import Business.SystemAdmin;
import FMCG.FMCG;
import FMCG.FMCGDirectory;
import FMCG.FmcgAdmin;
import Farmer.FarmerProfile;
import Distributor.Distributor;
import Distributor.DistributorAdmin;
import Distributor.DistributorUserAccount;
import PersonUserProfile.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sagar
 */
public class ViewDistriibutorUserDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewUserDetails
     */
    JPanel processStackjPanel;
    DistributorUserAccount selectedAccount;
    DistributorAdmin distributorAdmin;


    ViewDistriibutorUserDetails(DistributorUserAccount selectedUserAccount, JPanel processStackjPanel, DistributorAdmin distributorAdmin) {
       initComponents();
        this.processStackjPanel = processStackjPanel;
        this.selectedAccount = selectedUserAccount;
        this.distributorAdmin= distributorAdmin;
        populateUserFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblManageUser = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPersonID = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPersonID = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        txtProfile = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(224, 245, 166));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblManageUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblManageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUser.setText("User Details");

        lblName.setText("Name:");

        lblPersonID.setText("Person ID:");

        lblEmailID.setText("Email ID:");

        lblEnterpriseType.setText("Profile Type:");

        lblUserName.setText("User Name:");

        lblPassword.setText("Password:");

        txtName.setEnabled(false);

        txtPersonID.setEnabled(false);

        txtEmailID.setEnabled(false);

        txtProfile.setEnabled(false);

        txtUsername.setEnabled(false);

        txtPassword.setEnabled(false);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addComponent(lblPersonID)
                    .addComponent(lblEmailID)
                    .addComponent(lblEnterpriseType)
                    .addComponent(lblUserName)
                    .addComponent(lblName))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(txtName)
                    .addComponent(txtPersonID)
                    .addComponent(txtEmailID)
                    .addComponent(txtProfile)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPersonID)
                            .addComponent(txtPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailID)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnterpriseType))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPassword)
                        .addGap(6, 6, 6))
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        try {
            processStackjPanel.remove(this);
            Component[] componentArray = processStackjPanel.getComponents();
            Component component = componentArray[componentArray.length - 1];
            ManageDistUserAccountsJPanel manageUserAccountsJPanel = (ManageDistUserAccountsJPanel) component;
            //manageUserAccountsJPanel.refreshUserAccountTable();
            CardLayout layout = (CardLayout) processStackjPanel.getLayout();
            layout.previous(processStackjPanel);
            
        } catch (Exception e) {
            System.out.println("Exception in back button: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        txtName.setEnabled(true);
        txtEmailID.setEnabled(true);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if(txtName.getText().isBlank()|| txtPassword.getText().isBlank()|| txtUsername.getText().isBlank() || txtEmailID.getText().isBlank() || txtProfile.getText().isBlank())
            {
                JOptionPane.showMessageDialog(null, "Please fill all details.","Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{                
                selectedAccount.getAssociatedPersonProfile().getPerson().setFullName(txtName.getText());
                selectedAccount.getAssociatedPersonProfile().getPerson().setEmailId(txtEmailID.getText());
                selectedAccount.setUsername(txtUsername.getText());
                selectedAccount.setPassword(txtPassword.getText());
                btnSave.setEnabled(false);
                btnEdit.setEnabled(true);
                txtName.setEnabled(false);
                txtEmailID.setEnabled(false);
                txtUsername.setEnabled(false);
                txtPassword.setEnabled(false);
          }
        }
        catch (Exception e) {
            System.out.println("Exception while saving Information: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    public void populateUserFields() {
        try {
            txtName.setText(selectedAccount.getPersonName());
            txtPersonID.setText(String.valueOf(selectedAccount.getPersonId()));
            txtEmailID.setText(selectedAccount.getAssociatedPersonProfile().getPerson().getEmailId());
            txtProfile.setText(selectedAccount.getRole());
            txtProfile.setText(selectedAccount.getAssociatedPersonProfile().getRole());
            txtUsername.setText(selectedAccount.getUsername());
            txtPassword.setText(selectedAccount.getPassword());
            
        } catch (Exception e) {
            System.out.println("Exception while populating Information: " + e.getMessage());
      }   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblManageUser;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPersonID;
    private javax.swing.JTextField txtProfile;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
